Testing
[09:15:33, 02.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: connect ECONNREFUSED 87.240.190.70:443
[09:15:45, 02.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: connect ECONNREFUSED 87.240.190.70:443
[09:15:55, 02.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: connect ECONNREFUSED 87.240.190.70:443
[09:16:05, 02.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: connect ECONNREFUSED 87.240.190.70:443
[11:45:40, 02.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: connect ECONNREFUSED 192.168.0.1:443
[11:45:52, 02.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: connect ECONNREFUSED 192.168.0.1:443
[11:46:02, 02.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: connect ECONNREFUSED 192.168.0.1:443
[18:23:08, 02.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: connect ECONNREFUSED 87.240.139.193:443
[18:23:20, 02.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: connect ECONNREFUSED 87.240.139.193:443
[18:23:30, 02.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: connect ECONNREFUSED 87.240.139.193:443
[18:23:54, 02.09.2020] | [vk] >> Ошибка проверки new-users.json: network timeout at: https://api.vk.com/method/messages.getConversationMembers
[20:53:24, 02.09.2020] | [vk] >> Premium Not Started >> request to https://api.vk.com/method/groups.getById failed, reason: connect ECONNREFUSED 192.168.0.1:443
[20:53:24, 02.09.2020] | [vk] >> VK Not Started >> request to https://api.vk.com/method/groups.getById failed, reason: connect ECONNREFUSED 192.168.0.1:443
[20:53:24, 02.09.2020] | [vk] >> Creator Not Started >> request to https://api.vk.com/method/groups.getById failed, reason: connect ECONNREFUSED 192.168.0.1:443
[20:53:33, 02.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: connect ECONNREFUSED 192.168.0.1:443
[20:53:57, 02.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[08:03:26, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: Code №10 - Internal server error
[11:17:42, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: connect ECONNREFUSED 192.168.0.1:443
[11:17:54, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: connect ECONNREFUSED 192.168.0.1:443
[11:18:04, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: connect ECONNREFUSED 192.168.0.1:443
[11:18:22, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:11:56, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:11:57, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:12:06, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:12:16, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:12:26, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:12:36, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:12:46, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:12:56, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:13:06, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:13:16, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:13:26, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:13:36, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:13:46, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:13:56, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:14:06, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:14:16, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:14:26, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:14:36, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:14:46, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:14:56, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:15:06, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:15:16, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:15:27, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:15:36, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:15:46, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:15:57, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:16:06, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:16:16, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:16:27, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:16:36, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:16:46, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:16:56, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:17:06, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:17:16, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:17:26, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:17:36, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:17:46, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:17:56, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:18:06, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:18:16, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:18:26, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:18:37, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:18:46, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:18:56, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:19:07, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:19:16, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:19:26, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:19:37, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:19:47, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:19:56, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:20:07, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:20:17, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:20:27, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:20:37, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:20:47, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:20:57, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:21:07, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:21:17, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:21:27, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:21:37, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:21:47, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:21:57, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:22:07, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:22:17, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:22:27, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:22:37, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:22:47, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:22:57, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:23:07, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:23:17, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:23:27, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:23:37, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:23:47, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:23:57, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:24:07, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:24:17, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:24:27, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:24:37, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:24:47, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:24:57, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:25:07, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:25:17, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[15:25:27, 03.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[21:27:39, 04.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: connect ECONNREFUSED 87.240.137.207:443
[21:27:52, 04.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: connect ECONNREFUSED 87.240.137.207:443
[21:28:02, 04.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: connect ECONNREFUSED 87.240.137.207:443
[21:28:20, 04.09.2020] | [vk] >> Ошибка проверки new-users.json: network timeout at: https://api.vk.com/method/messages.getConversationMembers
[06:42:29, 05.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[06:42:29, 05.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[06:42:39, 05.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[06:42:49, 05.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[06:42:59, 05.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[06:43:09, 05.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[11:48:52, 05.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[11:48:52, 05.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[11:49:02, 05.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[11:49:12, 05.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[11:49:22, 05.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[11:49:32, 05.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[12:11:43, 05.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[12:11:43, 05.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[12:11:53, 05.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[12:12:03, 05.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[12:12:13, 05.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[12:12:23, 05.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[12:12:33, 05.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[14:48:46, 05.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: connect ECONNREFUSED 87.240.190.75:443
[14:48:59, 05.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: connect ECONNREFUSED 87.240.190.75:443
[14:49:09, 05.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: connect ECONNREFUSED 87.240.190.75:443
[14:49:25, 05.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: connect ETIMEDOUT 87.240.190.75:443
[10:45:51, 07.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[10:45:52, 07.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[16:57:29, 07.09.2020] | [vk] >> Ошибка проверки new-users.json: Code №10 - Internal server error: Unknown error, try later
[20:18:53, 07.09.2020] | [vk] >> Ошибка проверки new-users.json: network timeout at: https://api.vk.com/method/messages.getConversationMembers
[20:18:55, 07.09.2020] | [vk] >> Ошибка проверки new-users.json: network timeout at: https://api.vk.com/method/messages.getConversationMembers
[20:19:06, 07.09.2020] | [vk] >> Ошибка проверки new-users.json: network timeout at: https://api.vk.com/method/messages.getConversationMembers
[20:19:22, 07.09.2020] | [vk] >> Ошибка проверки new-users.json: Response timeout while trying to fetch https://api.vk.com/method/messages.getConversationMembers (over 10000ms)
[20:19:37, 07.09.2020] | [vk] >> Ошибка проверки new-users.json: network timeout at: https://api.vk.com/method/messages.getConversationMembers
[20:19:37, 07.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[20:19:37, 07.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[20:19:47, 07.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[20:19:48, 07.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[20:19:57, 07.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[20:20:07, 07.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[20:20:17, 07.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[20:20:27, 07.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[20:20:37, 07.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[20:20:47, 07.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[20:20:57, 07.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[20:21:07, 07.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[20:21:17, 07.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[20:21:27, 07.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[20:21:37, 07.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[20:21:47, 07.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[20:21:57, 07.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[20:22:07, 07.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[20:22:17, 07.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[20:22:27, 07.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[20:22:37, 07.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[20:22:47, 07.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[20:22:57, 07.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[20:23:08, 07.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[20:23:17, 07.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[20:23:27, 07.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[20:23:37, 07.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[20:23:47, 07.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[20:23:57, 07.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[20:24:07, 07.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[08:37:44, 08.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[08:37:48, 08.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[08:37:50, 08.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[08:37:55, 08.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[08:38:04, 08.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[08:38:13, 08.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[08:38:23, 08.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[08:38:33, 08.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[08:38:43, 08.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[08:38:53, 08.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[08:39:03, 08.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[08:39:13, 08.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[08:39:23, 08.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[08:39:33, 08.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[08:39:43, 08.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[08:39:53, 08.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[08:40:03, 08.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[08:40:13, 08.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[08:40:23, 08.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[08:40:33, 08.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[08:40:43, 08.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[08:40:53, 08.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[08:41:03, 08.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[16:45:39, 10.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[16:45:39, 10.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[16:45:49, 10.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[16:45:59, 10.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[16:46:09, 10.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[16:46:19, 10.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[16:46:29, 10.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[16:46:39, 10.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[16:46:49, 10.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[16:46:59, 10.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[16:47:09, 10.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[16:47:19, 10.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[16:47:29, 10.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[16:47:39, 10.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com
[16:47:49, 10.09.2020] | [vk] >> Ошибка проверки new-users.json: request to https://api.vk.com/method/messages.getConversationMembers failed, reason: getaddrinfo ENOTFOUND api.vk.com